import { PeriodicElement } from '../interfaces/interfaces';
export const ELEMENT_DATA: PeriodicElement[] = [
  {
    Orden: 1,
    'Fecha creación': 'Hydrogen',
    'Fecha despacho': 1.0079,
    'Fecha entrega': 'H',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 2,
    'Fecha creación': 'Helium',
    'Fecha despacho': 4.0026,
    'Fecha entrega': 'He',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 3,
    'Fecha creación': 'Lithium',
    'Fecha despacho': 6.941,
    'Fecha entrega': 'Li',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 4,
    'Fecha creación': 'Beryllium',
    'Fecha despacho': 9.0122,
    'Fecha entrega': 'Be',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 5,
    'Fecha creación': 'Boron',
    'Fecha despacho': 10.811,
    'Fecha entrega': 'B',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 6,
    'Fecha creación': 'Carbon',
    'Fecha despacho': 12.0107,
    'Fecha entrega': 'C',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 7,
    'Fecha creación': 'Nitrogen',
    'Fecha despacho': 14.0067,
    'Fecha entrega': 'N',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 8,
    'Fecha creación': 'Oxygen',
    'Fecha despacho': 15.9994,
    'Fecha entrega': 'O',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 9,
    'Fecha creación': 'Fluorine',
    'Fecha despacho': 18.9984,
    'Fecha entrega': 'F',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 10,
    'Fecha creación': 'Neon',
    'Fecha despacho': 20.1797,
    'Fecha entrega': 'Ne',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 11,
    'Fecha creación': 'Sodium',
    'Fecha despacho': 22.9897,
    'Fecha entrega': 'Na',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 12,
    'Fecha creación': 'Magnesium',
    'Fecha despacho': 24.305,
    'Fecha entrega': 'Mg',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 13,
    'Fecha creación': 'Aluminum',
    'Fecha despacho': 26.9815,
    'Fecha entrega': 'Al',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 14,
    'Fecha creación': 'Silicon',
    'Fecha despacho': 28.0855,
    'Fecha entrega': 'Si',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 15,
    'Fecha creación': 'Phosphorus',
    'Fecha despacho': 30.9738,
    'Fecha entrega': 'P',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 16,
    'Fecha creación': 'Sulfur',
    'Fecha despacho': 32.065,
    'Fecha entrega': 'S',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 17,
    'Fecha creación': 'Chlorine',
    'Fecha despacho': 35.453,
    'Fecha entrega': 'Cl',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 18,
    'Fecha creación': 'Argon',
    'Fecha despacho': 39.948,
    'Fecha entrega': 'Ar',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 19,
    'Fecha creación': 'Potassium',
    'Fecha despacho': 39.0983,
    'Fecha entrega': 'K',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  },
  {
    Orden: 20,
    'Fecha creación': 'Calcium',
    'Fecha despacho': 40.078,
    'Fecha entrega': 'Ca',
    'Estado orden': 'string',
    'Almacen a entregar': 'string',
    'Fecha real de entrega': 'string',
    Valor: 123456,
    'Consecutivo nota pedido': 'string',
    'Estado nota pedido': 'string',
    'Tipo de entrega': 'string',
    'Operador (transportadora)': 'string',
    'Estado de integración': 'string',
    'Fecha de integración': 'string'
  }
];
